### ISSUE TITLE
Signal handler to capture stack of all goroutines

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#119]
It is often helpful to get a stack dump by sending `SIGQUIT` to a Go program (Ctrl+\ if attached with a terminal). Looking at blocked goroutines can help find live locks.

We could have a signal handler integration or other mechanism that would send a full stack trace to Sentry.

**Comment by l0nax** [comment]
Any updates on this @rhcarvalho?

**Comment by rhcarvalho** [comment]
@l0nax, I have not put further thoughts into this, it was just an idea. Do you have a concrete use case?

**Comment by l0nax** [comment]
It would be helpful for our current project to have a look over all go-routines.
Besides of that – we are currently working on it, because on Windows such core dumps aren't currently created – I'm unaware of the current support on sentry's side to show multiple Threads/Go-Routines.

We want, at least, to be able to upload those core dumps – but this is part of another issue.
