### ISSUE TITLE
Add custom exception type feauture

### ISSUE THREAD

**Issue by mariaefi29** [getsentry/sentry-go#249]
##  Summary
We would like to be able to add custom exception types to our errors that are sent to sentry.

## Motivation
Our errors have different types and we see these particaular types in sentry like *erros.errorString and *status.statusError.
![image](https://user-images.githubusercontent.com/25860669/84234882-a599f680-aafd-11ea-8494-964bf6d40177.png)
Frankly, we are not so interested in an underlying error type here. We would like to be able to see the type we provided, for example like `Internal error`, `Timeout error`, `Batch exceeded error`.

## Additional Context
These types are determined due to the following code when the exception is constructed itself.
```
event.Exception = []Exception{{
		Value:      cause.Error(),
		Type:       reflect.TypeOf(cause).String(),
		Stacktrace: stacktrace,
	}}
```
As you can see from here exception's type is predetermined for us and there is impossible to customise it. 
As a straightforward way, that would be great to send error type along with error in `sentry.CaptureException(err, errorType)` as an option. Or it can be an option func `WithErrorType func(err error) string` that determines the type depends on the error. It that option func is missing, we can use the default behaviour like `reflect.TypeOf(cause).String()`. These are just some ideas at the top of my head. 

Could we please discuss it?

**Comment by rhcarvalho** [comment]
Hi @mariaefi29!

What version of the SDK are you using? From the code snippet above, `reflect.TypeOf(cause).String()` suggests `v0.5.1` or earlier. We've changed how error chains are reported since them, updating to `v0.7.0` may improve your experience.

Could you please provide a code snippet with:
1. an example of how one of your error types is defined,
2. what you see in Sentry, and
3. what you would like to see instead

**Comment by mariaefi29** [comment]
Hi @rhcarvalho!

Thank you for the provided information! 

Yes, you are right, we are using v0.5.1. Let me please explore the new version a bit and I will get back to you!

**Comment by mariaefi29** [comment]
Hi @rhcarvalho!

I have upgraded sentry to the latest version v0.7.0. However, I have experienced the same issue.

![Screenshot 2020-07-27 at 11 33 26](https://user-images.githubusercontent.com/25860669/88521404-87308180-cffd-11ea-8fb2-54d35bf3335b.png)

In sentry code your determine exception now like:

```
event.Exception = append(event.Exception, Exception{
			Value:      err.Error(),
			Type:       reflect.TypeOf(err).String(),
			Stacktrace: ExtractStacktrace(err),
		})
```

So you predetermine the type for us and there is nothing we can to do to change it.

As you can see on the attached print screen, we see 3 error types:
1. *errors.errorString type. This happens when we send just usual error from errors.New()
2. *echo.HTTPError type. This error is from http server echo
3. *status.statusError. This error occurred from gRPC server.

For us error type is not so important here (we use tags to divide errors from grpc and http servers), but it is highlighted. For example, if we wanted to classify errors yourself, we can't do that.

We would like to see highlighted something more valuable what we can defined ourselves. For example, we encounter "response timing exceeded" error. So highlighted in blue we would like to see Response Timing Error. 

Like in your tutorial you can see RestrictedIPAddress err type:

![image](https://user-images.githubusercontent.com/25860669/88522799-93b5d980-cfff-11ea-9d2b-e372248a32a8.png)

**Comment by rhcarvalho** [comment]
@mariaefi29 the behavior you are describing is how Sentry works in every\* platform.

The exception in the example screenshot above is Python code, has type `RestrictedIPAddress` and was raised in `<module-name> in <function-name>`.
Similarly, one of your custom Go errors is of type `*status.statusError`, in `<package-name> in <function-name>`.

The second line/subtitle has the indicator of severity level and textual description of the error.

This is how the Sentry UI is built (title, subtitle, message): [getsentry/sentry:src/sentry/static/sentry/app/utils/events.tsx](https://github.com/getsentry/sentry/blob/4ca2cee2010e1fd37839a665832a2987b75739c4/src/sentry/static/sentry/app/utils/events.tsx)
And this is how the `culprit` is built (the subtitle for errors): [getsentry/sentry:src/sentry/culprit.py](https://github.com/getsentry/sentry/blob/4ca2cee2010e1fd37839a665832a2987b75739c4/src/sentry/culprit.py)

---

\* There are few platform-specific customizations.

## Sentry UI

> For us error type is not so important here (we use tags to divide errors from grpc and http servers), but it is highlighted.

I agree with you many times the error type is not the most important info. But sometimes having the error/exception name front and foremost is useful.

See https://github.com/getsentry/sentry/issues/17837. It points out the problem, but, since we can't just change it for everyone, there's no clear solution other than providing some project settings knob to flip the lines or some other design tweak.

If you have specific ideas on what behavior you want, please comment on https://github.com/getsentry/sentry/issues/17837 and/or file a new issue, or contribute a PR. Note that the more general feature of setting your own title etc would involve an addition to the [event ingestion API](https://develop.sentry.dev/sdk/unified-api/), changes to `getsentry/sentry` and SDKs.

## Workaround

> We would like to see highlighted something more valuable what we can defined ourselves. For example, we encounter "response timing exceeded" error. So highlighted in blue we would like to see Response Timing Error.

Until Sentry supports custom title, subtitle and message, one workaround that you can use is to change your events in `BeforeSend` to change the fields (type, value, etc) to your liking.
https://docs.sentry.io/error-reporting/configuration/filtering/?platform=go

Note that you can do much more than filter events, you can change events to your heart's content :)

## Event fingerprinting

> For example, if we wanted to classify errors yourself, we can't do that.

If by `classify` you meant grouping, then that's covered by `fingerprints`. If you use the SDK to set your own fingerprints you can determine how Sentry groups issues.
https://docs.sentry.io/data-management/event-grouping/
https://pkg.go.dev/github.com/getsentry/sentry-go?tab=doc#Scope.SetFingerprint

**Comment by rhcarvalho** [comment]
I'm going to close this considering that the original request,

> We would like to be able to add custom exception types to our errors that are sent to sentry.

can be done with `BeforeSend` today:

```go
sentry.Init(sentry.ClientOptions{
	BeforeSend: func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
		event.Exception[0].Type = "custom type"
		return event
	},
})
```

Alternatively, for more granular control, the same effect can be achieved with an event processor on the scope:

```go
sentry.WithScope(func(scope *sentry.Scope) {
	scope.AddEventProcessor(func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
		event.Exception[0].Type = "custom type"
		return event
	})
	sentry.CaptureException(errors.New("Some Now Error"))
})
```

![image](https://user-images.githubusercontent.com/88819/88536166-99b1b780-d00b-11ea-817f-9902b2e420e7.png)

**Comment by mariaefi29** [comment]
@rhcarvalho 

Thank you very much for such a detailed and helpful response! We appreciate it so much! 
I believe we can work with this for now! Have a good day!

**Comment by pablodz** [comment]
should be in docs or readme

**Comment by vancluever** [comment]
For anyone else coming to this thread: you should be cognizant that the Sentry SDK seems to unroll wrapped errors and as such if you want to manipulate the name that shows up you will want to access the element at the _top_ of the event stack:

```
e.Exception[len(e.Exception)-1].Type = "custom type"
```

Referencing `e.Exception[0]` will update the name on the bottom of the stack which is likely not what you want (and ironically, has a much larger chance now of being a useful error type).

**Comment by jmrepetti** [comment]
A bit old, but If you implement the Error interface in your type (or you have a custom type for your errors) the name of your type will show as title in the Sentry UI. You'll see something like <module>.<YourTypeName>

For us was enough, and you just capture and send your custom error type with sentry.CaptureException(err).

**Comment by mariaefi29** [comment]
Thank you, everybody! I have changed the company and in my team we don't use sentry anymore. But if we do, I know where to go to for valuable advice! Thank you!

**Comment by emranbm** [comment]
For those looking for an out of the box workaround:
```go
func fixErrorEventContent(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
	if len(event.Exception) == 0 {
		return event
	}
	lastSentryException := event.Exception[len(event.Exception)-1]
	errorMessage := lastSentryException.Value
	errorSummary := strings.Split(errorMessage, ":")[0]
	logMessage := event.Message
	event.Message = errorMessage
	sentrySummaryRecord := sentry.Exception{
		Type:       logMessage,
		Value:      errorSummary,
		Module:     lastSentryException.Module,
		ThreadID:   lastSentryException.ThreadID,
		Stacktrace: lastSentryException.Stacktrace,
		Mechanism:  lastSentryException.Mechanism,
	}
	event.Exception = append(event.Exception, sentrySummaryRecord)
	return event
}
```
And configure the hook to use it:
```go
sentryHook, err := sentrylogrus.New(sentryLevels, sentry.ClientOptions{
		Dsn:              "...",
		BeforeSend:       fixErrorEventContent,
	})
```

**Comment by acevedomiguel** [comment]
> For those looking for an out of the box workaround:
> 
> func fixErrorEventContent(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
> 	if len(event.Exception) == 0 {
> 		return event
> 	}
> 	lastSentryException := event.Exception[len(event.Exception)-1]
> 	errorMessage := lastSentryException.Value
> 	errorSummary := strings.Split(errorMessage, ":")[0]
> 	logMessage := event.Message
> 	event.Message = errorMessage
> 	sentrySummaryRecord := sentry.Exception{
> 		Type:       logMessage,
> 		Value:      errorSummary,
> 		Module:     lastSentryException.Module,
> 		ThreadID:   lastSentryException.ThreadID,
> 		Stacktrace: lastSentryException.Stacktrace,
> 		Mechanism:  lastSentryException.Mechanism,
> 	}
> 	event.Exception = append(event.Exception, sentrySummaryRecord)
> 	return event
> }
> 
> And configure the hook to use it:
> 
> sentryHook, err := sentrylogrus.New(sentryLevels, sentry.ClientOptions{
> 		Dsn:              "...",
> 		BeforeSend:       fixErrorEventContent,
> 	})

I added the fingerprint to have a nice grouping by Type
```
event.Fingerprint = []string{
	"{{ default }}",
	logMessage,
}
return event
```
