### ISSUE TITLE
[0.9.0] wrong root span operation name in UI

### ISSUE THREAD

**Issue by yonderblue** [getsentry/sentry-go#318]
## Summary
See title

## Steps To Reproduce

```go
func main() {
	ctx := context.Background()

	opts := sentry.ClientOptions{
		Debug:            true,
		TracesSampleRate: 1.0,
		Dsn:              "https://THE_DSN",
	}

	if err := sentry.Init(opts); err != nil {
		panic(err)
	}
	defer sentry.Flush(3 * time.Second)

	sp1 := sentry.StartSpan(ctx, "span 1", sentry.TransactionName("the transaction"))
	defer sp1.Finish()
	for i := 0; i < 2; i++ {
		sp2 := sp1.StartChild("span 2")
		sp2.SetTag("a name", "a value")

		time.Sleep(time.Millisecond * 100)

		sp3 := sp2.StartChild("span 3")

		time.Sleep(time.Millisecond * 100)

		sp4 := sp3.StartChild("span 4")

		time.Sleep(time.Millisecond * 400)

		sp4.Finish()

		sp3.Finish()

		sp2.Finish()
	}
}
```

## Expected Behavior
The first span operation name in the code is `span 1` but in the UI is showing as `span 4`.
Note that if you remove the `sentry.TransactionName("the transaction")` the `span 1` appears but of course the transaction name is `unamed transaction` which is no good when you need transaction grouping, so not really a workaround.

## Screenshots

<img width="1118" alt="Screen Shot 2021-01-13 at 4 31 45 PM" src="https://user-images.githubusercontent.com/984510/104513348-84324900-55bd-11eb-885a-4fd4d669d0fd.png">

## Environment
sentry pkg at 0.9.0

### Sentry
 - Using hosted Sentry in sentry.io? yes

**Comment by Pr0Ger** [comment]
Removing `sentry.TransactionName` doesn't fix issue for me. Root span in transaction is always replaced with latest span.

I dug up a little and this is happening here, until this moment `event.context.trace` contain proper info about the root span: https://github.com/getsentry/sentry-go/blob/362a80dcc41f9ad11c8df556104db3efa27a419e/client.go#L558-L563

And this is happening because here we update scope with info about new span here and because of this aforementioned code will update `event.context.trace` with invalid info when sending event https://github.com/getsentry/sentry-go/blob/362a80dcc41f9ad11c8df556104db3efa27a419e/tracing.go#L149-L151

Probably this can be fixed by making this `SetContext` conditional on `isTransaction` field but I'm not sure if this will not break anything else.

btw looks like context.trace field is not documented here https://develop.sentry.dev/sdk/event-payloads/contexts/
