### ISSUE TITLE
[0.9.0] (*Span).sample() called before finished

### ISSUE THREAD

**Issue by yonderblue** [getsentry/sentry-go#320]
The `func (s *Span) sample() Sampled` func is called when a span is started, not when it is finished. This means the EndTime can not be used to determine a sampling decision in TracesSampler.

Perhaps this is more of a feature request but I'm not sure the current behavior was intentional.

**Comment by rhcarvalho** [comment]
@yonderblue the behavior in intentional. [Sentry's tracing model is head-based](https://docs.sentry.io/product/performance/distributed-tracing/#consistency-within-a-trace).
The sampling decision for a span is propagated to other services while the span is ongoing.
This is not fully implemented yet in the Go SDK, pending instrumentation for the HTTP client.
