### ISSUE TITLE
Remove Iris

### ISSUE THREAD

**Issue by carlmjohnson** [getsentry/sentry-go#334]
## Summary
Iris is well documented to be run by a dishonest person. Even a cursory look at it reveals that much of its code is stolen. Here is a summary of the case: https://www.reddit.com/r/golang/comments/b481q7/a_warning_about_githubcomkatarasiris/

The problem is that I want to be able to include sentry-go in my project without indirectly relying on Iris not somehow getting its stolen code into my repositories.

## Steps To Reproduce
In an empty directory:

```
$ go mod init project
go: creating new go.mod: module project

$ go get -v github.com/getsentry/sentry-go
github.com/getsentry/sentry-go/internal/crypto/randutil
github.com/getsentry/sentry-go/internal/debug
github.com/getsentry/sentry-go
go get: added github.com/getsentry/sentry-go v0.10.0

$ cat go.sum | grep iris
github.com/iris-contrib/blackfriday v2.0.0+incompatible/go.mod h1:UzZ2bDEoaSGPbkg6SAB4att1aAwTmVIx/5gCVqeyUdI=
github.com/iris-contrib/go.uuid v2.0.0+incompatible/go.mod h1:iz2lgM/1UnEf1kP0L/+fafWORmlnuysV2EMP8MW+qe0=
github.com/iris-contrib/jade v1.1.3/go.mod h1:H/geBymxJhShH5kecoiOCSssPX7QWYH7UaeZTSWddIk=
github.com/iris-contrib/pongo2 v0.0.1/go.mod h1:Ssh+00+3GAZqSQb30AvBRNxBx7rf0GqwkjqxNd0u65g=
github.com/iris-contrib/schema v0.0.1/go.mod h1:urYA3uvUNG1TIIjOSCzHr9/LmbQo8LrOcOqfqxa4hXw=
github.com/kataras/iris/v12 v12.1.8/go.mod h1:LMYy4VlP67TQ3Zgriz8RE2h2kMZV2SgMYbq3UhfoFmE=
```

## Expected result

No stolen code.

## Actual result

Several obviously stolen projects.

**Comment by rhcarvalho** [comment]
Hi @carlmjohnson. The [`go.sum` file contains cryptographic hashes of modules](https://golang.org/ref/mod#go).

It does not include any source code, nor does it add any code to your binaries (of course unless you actually use the Iris framework, and the `github.com/getsentry/sentry-go/iris` package in your own project).

Related to #156. Separating out framework integrations from the core SDK module would possibly create less confusion, since the core SDK has no runtime dependencies outside of the standard library.

Hope that helps clarify the situation, please let me know if I can help in any other way.

**Comment by hughevans** [comment]
I’d like iris removed because of [CVE-2020-15114](https://nvd.nist.gov/vuln/detail/CVE-2020-15114) for which there is no [stable release of Iris](https://github.com/kataras/iris/releases) without its dependencies updated.

**Comment by rhcarvalho** [comment]
> I’d like iris removed because of [CVE-2020-15114](https://nvd.nist.gov/vuln/detail/CVE-2020-15114) for which there is no [stable release of Iris](https://github.com/kataras/iris/releases) without its dependencies updated.

This is due to how `dependabot` creates false positives by [erroneously treating `go.sum` as a lock file](https://github.com/golang/go/wiki/Modules#is-gosum-a-lock-file-why-does-gosum-include-information-for-module-versions-i-am-no-longer-using).

If your program (`main` package) doesn't use `github.com/kataras/iris` nor `github.com/getsentry/sentry-go/iris` then the Iris source code is never downloaded (true for all recent/supported Go versions), none of its dependencies affect version selection of your dependencies ([since Go 1.17 added Module Graph Pruning](https://go.dev/doc/go1.17#graph-pruning)), and you can safely ignore/dismiss `dependabot`.

**Comment by carlmjohnson** [comment]
Okay, but the core issue remains: Iris is a fake, stolen project. There is no need for Sentry to refer to it, however peripherally. It’s like Sentry having a link to the Pirate Bay on the list of issue. “You don’t have to click that link.” Yes, but you don’t have to include that link either.

**Comment by hughevans** [comment]
@rhcarvalho Thanks for that, in this case it was [Nancy](https://github.com/sonatype-nexus-community/nancy) that was detecting. Your comment [here](https://github.com/getsentry/sentry-go/issues/156#issuecomment-802656143) clarified the situation nicely, but I needed a workaround so I just added this into our `go.mod`:

```
exclude (
	github.com/kataras/iris/v12 v12.1.8
	github.com/labstack/echo/v4 v4.1.11
)
```
