### ISSUE TITLE
Set events fingerprint from errors when possible

### ISSUE THREAD

**Issue by shouichi** [getsentry/sentry-go#374]
## Summary

Set events fingerprint from errors when they have `Fingerprint` method.

### Background

SDK allows grouping errors by fingerprinting errors. The current way of fingerprinting errors is to use `ClientOptions.BeforeSend`.

https://docs.sentry.io/platforms/go/usage/sdk-fingerprinting/

```
sentry.Init(sentry.ClientOptions{
	// ...
	BeforeSend: func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
		if ex, ok := hint.OriginalException.(MyRPCError); ok {
			event.Fingerprint = []string{"{{ default }}", ex.ErrorCode(), ex.FunctionName()}
		}

		return event
	},
})
```

While this works but it has the following drawbacks.

- Custom error types must be public.
- Tedious type assertions when there are many error types.

### Proposal

Set fingerprint automatically if an error satisfies the "fingerprinter" interface when building an event from the error.

```
event := NewEvent()
event.Level = level
...

type fingerprinter interface {
	Fingerprint() []string
}

if f, ok := err.(fingerprinter); ok {
	event.Fingerprint = f.Fingerprint()
}
```

This should solve the above drawbacks of the current approach. Minor note: it might be better to name the method `SentryFingerprint` to avoid conflicts.

Any feedback would be appreciated. Thanks in advance.

**Comment by rhcarvalho** [comment]
Hi @shouichi! Thanks for the proposal. My thoughts:

`Fingerprinter` is not a broadly used interface, you won't find library errors implementing this interface. It means that for anyone to actually benefit from this they'd need to change their code to add a new method to their error types, and still would not work for other error types they don't control.

I believe discovering the `Fingerprinter` interface and changing code to use it is less likely to happen than customizing the fingerprint in `BeforeSend`.

For those who actually want to add "custom fingerprint behavior" to their errors, your proposal is a fine idea, an idea that can be implemented without changes to the SDK:

<details>
<summary><code>example.go</code></summary>

```go
package main

// import ...

type fingerprinter interface {
	Fingerprint() []string
}

type myError struct{}

func (myError) Error() string {
	return "internal error"
}

func (myError) Fingerprint() []string {
	return []string{"custom", "fingerprint"}
}

func main() {
	// ...
	sentry.Init(sentry.ClientOptions{
		// ...
		BeforeSend: func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
			if f, ok := err.(fingerprinter); ok {
				event.Fingerprint = f.Fingerprint()
			}
			return event
		},
	})
}
```

</details>

Regarding the drawbacks you listed:

> * Custom error types must be public.

If you use interfaces as in your proposal, error types do not need to be exported.
If your error types are defined in the same package as your `BeforeSend` func, they also do not need to be exported, and even their custom fingerprint could be made non-exported (`fingerprint() []string` instead of `Fingerprint() []string`).

> * Tedious type assertions when there are many error types.

With or without the proposal, there still needs to be explicit code somewhere to specify what the fingerprint is, so it is a user choice how they want to go about it. They can use a type assertion with a concrete type, a type assertion with an interface, a type switch, or reflection, etc.

Also note that you can reuse the pattern in multiple programs:

<details>
<summary><code>reusable package example</code></summary>

Create a package for reuse:

```go
package fingerprinter // import "example.com/fingerprinter"

import "github.com/getsentry/sentry-go"

type Interface interface {
	Fingerprint() []string
}

func Wrap(original sentry.EventProcessor) sentry.EventProcessor {
	return func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
		if event == nil || hint == nil {
			return original(event, hint)
		}
		if f, ok := hint.OriginalException.(Interface); ok {
			event.Fingerprint = f.Fingerprint()
		}
		return original(event, hint)
	}
}
```

Then in package `main`:

```go
package main

import (
	"example.com/fingerprinter"
	"github.com/getsentry/sentry-go"
)

type myError struct{}
// TODO: Implement Error() and Fingerprint() methods

// Ensure myError implements fingerprinter.Interface.
var _ fingerprinter.Interface = &myError{}

func main()
	// ...
	sentry.Init(sentry.ClientOptions{
		BeforeSend: fingerprinter.Wrap(func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
			// custom logic here...
			return event
		}),
	})
	// ...
}
```

</details>

**Comment by shouichi** [comment]
> For those who actually want to add "custom fingerprint behavior" to their errors, your proposal is a fine idea, an idea that can be implemented without changes to the SDK:

This makes a lot of scenes to me. Thank you very much for the detailed explanation! I'm closing this.
