### ISSUE TITLE
go.sum contains reference (via Echo framework integration) to module affected by CVE

### ISSUE THREAD

**Issue by erlichmen** [getsentry/sentry-go#376]
sentry-go is using a rather old version of the [echo](https://github.com/labstack/echo) module which uses a JWT module that has a [CVE](https://github.com/advisories/GHSA-w73w-5m7g-f7qc) (the latest (since July 2020) echo module has resolve that). 
This causes our repo to raise a flag and that makes the chain of brass itchy.

The only solution right now is to *remove* sentry  and we really don't want it.

**Comment by bww** [comment]
Same problem here, we don't want to fork your client and we can't just ignore this. It's fairly surprising for this not to have been addressed by now, especially given what your product does. Don't you guys get the Dependabot alerts about this?

Version 4.5.0 of echo has fixed the problem, you should be able to just bump the version:
https://github.com/labstack/echo/blob/v4.5.0/go.sum

**Comment by rhcarvalho** [comment]
> This causes our repo to raise a flag and that makes the chain of brass itchy.

@erlichmen what tool are you using that flags this as an issue?

I would like to see if we can make some tools smarter -- notice that [`go.sum` is not a lock file](https://github.com/golang/go/wiki/Modules#is-gosum-a-lock-file-why-does-gosum-include-information-for-module-versions-i-am-no-longer-using), but some tools treat it like so. The `go.sum` file is a database of module cryptographic hashes, and the modules/versions listed there are not necessarily part of your build dependencies.

From the main package directory, use `go list all` to see the build dependencies (and prior to Go 1.16 that also includes the test dependencies of all dependencies).

---

> Dependabot alerts about this

@bww do you have an example of alert/PR in a public repo? I'd love to use that to open an issue in https://github.com/dependabot/dependabot-core.

It used to be the case (based on [this comment from a core Dependabot developer](https://github.com/dependabot/dependabot-core/issues/2229#issuecomment-430684330)) that Dependabot dit not have access to the complete source code required to run `go list ./...` to determine potential outdated or problematic dependencies.

But since that [issue was closed](https://github.com/dependabot/dependabot-core/issues/2229#issuecomment-712254324) and they run `go mod tidy` maybe it would also be possible to determine actual dependencies using `go list` instead of `go.mod`/`go.sum`. (Reference: https://github.com/dependabot/dependabot-core/tree/main/go_modules)

**Comment by phmx** [comment]
Could you please bump the sentry-go release tag to incorporate this update?
