### ISSUE TITLE
How to Track Transaction Across Various Go Service?

### ISSUE THREAD

**Issue by ROMOSU** [getsentry/sentry-go#463]
For the gRPC service (without official plugin), we needs to track the transaction between services, so how to set `TraceID` to ensure they are under the same transaction?

**Comment by smeubank** [comment]
Do you have the `TracesSampleRate` or `TracesSampler` set in your application?

[Sentry Go Performance and Distributed tracing](https://docs.sentry.io/platforms/go/performance/)

https://docs.sentry.io/platforms/go/performance/connect-services/

**Comment by smeubank** [comment]
let us know if there was something more to your question, and we will try to help. Otherwise we will close the issue for now.

**Comment by sebastiaopamplona** [comment]
Hi @smeubank , I have an application that uses gRPC micro services, and I'm trying to implement distributed tracing.
So it has an HTTP server for the api, which then talks gRPC with other microservices.

### HTTP Middleware
In my HTTP server, I have a middleware that stars a Span and adds the TraceID to the gRPC context (which is propagated to the other gRPC microservices):
```go
// Create span with the endpoint name.
span := sentry.StartSpan(ctx, endpoint, sentry.TransactionName(endpoint))
defer span.Finish()

(...)

// Add TraceID to the gRPC context so that other microservices
// can attach spans to the same Trace.
ctx = context.WithValue(ctx, TraceIDContextKey, span.TraceID.String())

// Make gRPC call 1.
_, _ = cartClient.AddToCart(ctx, &cartProto.AddToCartRequest{...})

// Make gRPC call 2.
_, _ = cartClient.Checkout(ctx, &cartProto.CheckoutRequest{...})
```

### gRPC Client Interceptor
I have a client interceptor that also creates a Span, using the TraceID injected in the context:
```go
func UnaryClientInterceptor() grpc.UnaryClientInterceptor {
	return func(
		ctx context.Context,
		method string,
		req, reply interface{},
		cc *grpc.ClientConn,
		invoker grpc.UnaryInvoker,
		callOpts ...grpc.CallOption,
	) error {
		// Fetch TraceID from context.
		traceID, ok := ctx.Value(TraceIDContextKey).(string)
		if ok {
			span := sentry.StartSpan(
				ctx,
				method,
				sentry.TransactionName(method),
				// This will attach the Span to the Trace with the TraceID.
				sentry.ContinueFromTrace(traceID),
			)
			defer span.Finish()
		}

		return invoker(ctx, method, req, reply, cc, callOpts...)
	}
}
```

### gRPC Server Interceptor
```go
func UnaryServerInterceptor() grpc.UnaryServerInterceptor {
	return func(
		ctx context.Context,
		req interface{},
		info *grpc.UnaryServerInfo,
		handler grpc.UnaryHandler,
	) (interface{}, error) {
		// Fetch TraceID from context.
		traceID, ok := ctx.Value(TraceIDContextKey).(string)
		if ok {
			span := sentry.StartSpan(
				ctx,
				info.FullMethod,
				sentry.TransactionName(info.FullMethod),
				// This will attach the Span to the Trace with the TraceID.
				sentry.ContinueFromTrace(traceID),
			)
			defer span.Finish()
		}
		return handler(ctx, req)
	}
}
```

### Expected behaviour
What I expect is to see 1 single trace with the TraceID generated from the first span in the HTTP middleware, containing 5 Spans inside:
1. Span generated in the HTTP middleware
2. Span generated in the client interceptor of first gRPC call `cartClient.AddToCart`
3. Span generated in the server interceptor of first gRPC call `cartClient.AddToCart`
4. Span generated in the client interceptor of second gRPC call `cartClient.Checkout`
5. Span generated in the server interceptor of second gRPC call `cartClient.Checkout`


### Actual behaviour
I only see 1 Span, corresponding to the Span generated by the `UnaryServerInterceptor` (somehow, the first 2 don't appear in Sentry).

This is my init function:
```go
	err := sentry.Init(sentry.ClientOptions{
		EnableTracing:    true,
		AttachStacktrace: false,
		Dsn:              "url of sentry",
		// Set TracesSampleRate to 1.0 to capture 100%
		// of transactions for performance monitoring.
		// We recommend adjusting this value in production,
		TracesSampleRate: 1.0,
		ServerName:       serviceName,
		Environment:      "development",
	})

	defer sentry.Flush(2 * time.Second)

	if err != nil {
		return err
	}

	return nil
```
