### ISSUE TITLE
Sentry does not report errors in dockers scratch image

### ISSUE THREAD

**Issue by mwohlert** [getsentry/sentry-go#63]
When using sentry in a go project, which is statically compiled and executed in a docker scratch image sentry captured errors will not end up in the webinterface.

**Comment by mwohlert** [comment]
Example: https://github.com/mwohlert/sentry_scratch_golang

**Comment by mattrobenolt** [comment]
My first guess is because you're lacking SSL certificates in `scratch`. We document how to work around this here: https://docs.sentry.io/platforms/go/migration/#providing-ssl-certificates

In raven-go, we used to bundle this by default and always use certifi for certificates, but this proved to be very controversial and we chose to just document it for the relatively rare situations where there aren't any certificates available.
