### ISSUE TITLE
Performance tracing sends transactions but do not show up in web interface

### ISSUE THREAD

**Issue by connormullett** [getsentry/sentry-go#703]
## Summary

We currently have a set of microservices that we want to enable tracing on. It is a Golang service using Gin and Gorm. For simplicity we have opted to use sentry; However, we are not seeing the traces in the performance tab in the web interface. The logs indicate that transactions are being sent, and we can even see issues linked to a transaction using the `hub` instance but no trace exists. We assumed that `sentrygin` automatically creates the spans as other libraries do but even following the guide for custom instrumentation and initializing spans does not work.

## Steps To Reproduce

Here's a snippet from main. Unfortunately, our code base is private and not able to link the full project for additional help. Prior to this we were using a `sentrylogrus` hook and changed it to the below in hopes of it working. 

```go
err := sentry.Init(sentry.ClientOptions{
  Dsn:              "our dsn",
  EnableTracing:    true,
  AttachStacktrace: true,
  SampleRate:       1.0,
  TracesSampleRate: 1.0,
  MaxBreadcrumbs:   100,
  Environment:      "env",
})

if err != nil {
  logger.Fatalf("sentry init: %s", err)
}
defer sentry.Flush(2 * time.Second)

router.Use(sentrygin.New(sentrygin.Options{}))

route.GET("/health", func(ctx *gin.Context) {
  span := sentry.StartSpan(ctx.Request.Context(), "health")
  ctx.JSON(http.StatusOK, gin.H{"live": "ok"})
  span.Finish()
})
```

## Expected Behavior

We are able to see traces in the web interface on the projects performance page

## Environment

gin version v1.9.1

### SDK
 - `sentry-go` version: v0.23.0
 - Go version: 1.20
 - Using Go Modules? [yes]

### Sentry
 - Using hosted Sentry in sentry.io? [no]

**Comment by tonyo** [comment]
The problem is actually related to the fact that we're currently dropping certain groups of healthcheck-related transactions on the server side by default: https://docs.sentry.io/product/data-management-settings/filtering/#transactions-coming-from-healthcheck
This can be turned off by going to `Project Settings > Inbound Filters" and disabling `Filter out health check transactions`.

Could you check if turning off that option works for you? Other transaction URLs should be handled normally.

We're aware that the user experience is not ideal, and at some point we're going to add additional hints about those types of transactions being filtered.

**Comment by connormullett** [comment]
Considering we have other routes in place, I opted to not fiddle with the settings for healthcheck routes. It makes sense that it filters it (especially when you have limited transactions per month). I tried adding the span to another route and hit it with postman and confirmed that this works. Thanks for the assist
