### ISSUE TITLE
Profiling large number of goroutines

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-go#748]
I've created a simple [sample application](https://github.com/getsentry/sentry-go/tree/chore/profiling-many-routines/_examples/profiling-many-routines) with 5000 concurrent goroutines, tuned to have around 30 % CPU usage (on my desktop PC) without profiling. After profiling was enabled with 5 % sample rate, the CPU usage jumps to around 40 %.

I've run a pprof CPU profile with and without profiling enabled. In the following SVG, you can see that the vast majority of the overhead is coming from calling `Runtime.stack()`. Current profiling implementation calls it periodically to collect stacks for all goroutines. Therefore, the time complexity increases with the number of active goroutines. 
[See the profile output as a tree (.svg so you can zoom in)](https://github.com/getsentry/sentry-go/assets/6349682/b841b712-fcf9-4632-9fba-fe9fb1ba5733)

I'm investigating how we could improve this.

Note: `runtime.GoroutineProfile()` has lower overhead, possibly because it doesn't produce string output, but it currently doesn't have a goroutine ID so we can't map stacks across multiple calls to a single routine, see https://github.com/golang/go/issues/59663

**Comment by vaind** [comment]
With the current tooling we have available from Go runtime and in combination with what Sentry.io expects to receive, I don't see a way to improve profiling for apps with a very large number of goroutines.
If we could make Sentry accept pprof (which only has aggregate information about samples), we could use `pprof.StartCPUProfile()`. This, however, would not yield the same experience as with other SDKs because we wouldn't have time-based samples anymore. A big downside to this would be that adding another format would introduce future maintenance issues when trying to keep it working alongside the "mainstream" sampling profiler.

As such, I think we may want to make some adjustments to automatically disable the profiler when it encounters a given number of goroutines. This would act as a reasonable default behaviour working around this limitation before it's resolved in one way or another. Users could be able to change this configuration or disable it completely if they want to run the profiler unhindered, regardless of the number of routines they launch.

**Comment by vaind** [comment]
I've made a [PR in Go](https://go-review.googlesource.com/c/go/+/585396) to land the change to GoroutineProfile() and verified the functionality in the SDK on branch https://github.com/getsentry/sentry-go/tree/feat/goroutine-profile

**Comment by cleptric** [comment]
Sweet!

**Comment by karatekaneen** [comment]
We think we're encountering the same issue with some memory leak regarding profiling.

Here we're running the same application under roughly the same load, the only difference is that we've disabled profiling. The version of `sentry-go` is `0.27.0` but from looking at the changelogs there doesn't seem to be any changes regarding profiling in the latest version.
![Image](https://github.com/user-attachments/assets/1680acab-9f91-473d-8d3f-b51ac6742aa4)

**Comment by cleptric** [comment]
We removed profiling from the SDK for the time being.

**Comment by kainosnoema** [comment]
@cleptric any indication when to expect the Go profiling to be fixed? We've been holding off upgrading the SDK so we don't lose profiling...

**Comment by DarkByteZero** [comment]
We also still want to use profiling, even if it has issues with a high number of goroutines. I don’t understand why it was removed altogether instead of providing an option for users to enable it at their own risk. Because of this, we are also holding off on updating the SDK for now. Is there any chance of bringing profiling back as an optional feature?

**Comment by gunnsth** [comment]
I wanted to enable this in some of my applications and was disappointed to see that this has been removed.  We don't normally have that high number of go routines, so wouldn't expect to be affected by the performance issue.

It would be very beneficial to have this feature.  It's off by default, and marked as experimental, so I guess people shouldn't enable it in such cases.

Hopefully the needed changes will land in Go soon so that this can be implemented.  The value of this is very high.  The performance is critical of course.  It'd be better if it captures less, but something at least.  Would it be possible to only look at the stack trace for a limited number of go routines?

It would make sense to check how profiling with the built in profiler handles those cases (5000 goroutines).  That would form a good baseline.

**Comment by DarkByteZero** [comment]
@gunnsth If you downgrade you can still use the feature, it works without a problem, profiles are ingested.

**Comment by vaind** [comment]
> It would make sense to check how profiling with the built in profiler handles those cases (5000 goroutines). That would form a good baseline.

The builtin profiler has access to the missing info so it doesn't have the same issue. Also, we cannot just use the builtin profiler and use its output because the output is already aggregated and is not useful to our backend & UI

**Comment by cleptric** [comment]
Would anyone be happy if we would add profiling support via https://github.com/open-telemetry/opentelemetry-ebpf-profiler? Not making promises, just gauging interest.

**Comment by alkanna** [comment]
> Would anyone be happy if we would add profiling support via [open-telemetry/opentelemetry-ebpf-profiler](https://github.com/open-telemetry/opentelemetry-ebpf-profiler?rgh-link-date=2025-03-13T18%3A43%3A14.000Z)? Not making promises, just gauging interest.

We would, we are currently sticking to a previous version of the library with profiling still available because of this.
